CREATE TABLE `notice_me` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`reply` TEXT NOT NULL COLLATE 'latin1_swedish_ci',
	`added_by` TEXT NOT NULL COLLATE 'latin1_swedish_ci',
	`added_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;